# Generated by Django 5.0 on 2024-01-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blood_group',
        ),
        migrations.AddField(
            model_name='customuser',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(default=None),
        ),
    ]
