# Generated by Django 5.0.2 on 2024-03-18 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP_backend', '0003_alter_customuser_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='weight',
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cataract', models.IntegerField(default=0)),
                ('Gluocoma', models.IntegerField(default=0)),
                ('Normal', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
