# Generated by Django 5.0.2 on 2024-03-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP_backend', '0004_remove_customuser_activated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='Cataract',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='Gluocoma',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='Normal',
        ),
        migrations.AddField(
            model_name='disease',
            name='dname',
            field=models.CharField(default='Normal'),
        ),
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.CharField(default=None),
        ),
    ]
