# Generated by Django 5.0.2 on 2024-03-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DP_backend', '0005_remove_disease_cataract_remove_disease_gluocoma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.CharField(default='None'),
        ),
    ]
